import React from "react";
import { Formik, Form } from "formik";
import {
  Container,
  TextField,
  ToggleBtn,
  ToggleField,
  FlexDiv,
  Btn,
} from "./CreatePlaylistForm.styles";

const CreatePlaylistForm = ({ setShowSelect }) => (
  <Container>
    <Formik
      initialValues={{
        name: "",
        desc: "",
        public: true,
      }}>
      <Form>
        <label htmlFor='name'>Name of the playlist:</label>
        <TextField id='name' name='name' placeholder='Listify playlist' />

        <label htmlFor='desc'>Description:</label>
        <TextField
          id='desc'
          name='desc'
          placeholder='A playlist automatically generated by listify recommendations'
        />

        <ToggleField
          className='public'
          id='public'
          name='public'
          value={true}
        />
        <ToggleBtn for='public'>Public</ToggleBtn>
        <ToggleField
          className='private'
          id='private'
          name='public'
          value={false}
        />
        <ToggleBtn for='private'>Private</ToggleBtn>
        <FlexDiv>
          <Btn onClick={() => setShowSelect(true)}>Go back</Btn>
          <Btn type='submit'>Create</Btn>
        </FlexDiv>
      </Form>
    </Formik>
  </Container>
);

export default CreatePlaylistForm;
