import React from "react";
import { Formik, Form, Field } from "formik";

const CreatePlaylistForm = () => (
  <Formik
    initialValues={{
      name: "",
      desc: "",
      public: true,
    }}>
    <Form>
      <label htmlFor='name'>Name of the playlist:</label>
      <Field id='name' name='name' placeholder='Listify playlist' />

      <label htmlFor='desc'>Description:</label>
      <Field
        id='desc'
        name='desc'
        placeholder='A playlist automatically generated by listify recommendations'
      />

      <label>
        <Field type='radio' id='public' name='public' />
        Public playlist
      </label>

      <button type='submit'>Create</button>
    </Form>
  </Formik>
);

export default CreatePlaylistForm;
